# Generated by Django 3.2.4 on 2021-09-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whisky',
            old_name='bottle_type',
            new_name='cask_type',
        ),
        migrations.RemoveField(
            model_name='whisky',
            name='bottle_number',
        ),
        migrations.RemoveField(
            model_name='whisky',
            name='bottled',
        ),
        migrations.RemoveField(
            model_name='whisky',
            name='cask',
        ),
        migrations.RemoveField(
            model_name='whisky',
            name='cask_strength',
        ),
        migrations.RemoveField(
            model_name='whisky',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='whisky',
            name='vintage',
        ),
        migrations.AlterField(
            model_name='whisky',
            name='alcohol',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='whisky',
            name='independent_whisky',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='whisky',
            name='natural_color',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='whisky',
            name='non_chillfiltered',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
