# Generated by Django 3.2.4 on 2021-07-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whisky',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
