# Generated by Django 3.2 on 2021-06-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blocked_user',
            field=models.ManyToManyField(blank=True, related_name='user_blocked', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='user_followers', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='user_following', to='api.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='pending_request',
            field=models.ManyToManyField(blank=True, related_name='PendingRequest', to='api.Profile'),
        ),
    ]
