# Generated by Django 3.2.4 on 2021-07-20 04:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_whisky_bottled'),
    ]

    operations = [
        migrations.AddField(
            model_name='whisky',
            name='contributor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='WhiskyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.validate_image_file_extension])),
                ('whisky', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whisky_image', related_query_name='whisky_image', to='api.whisky')),
            ],
        ),
    ]
