# Generated by Django 3.2.4 on 2021-07-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210627_2303'),
        ('api', '0002_whisky_confirmed'),
    ]

    operations = [
    ]
