# Generated by Django 3.1.5 on 2021-05-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210505_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Whisky',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('whisky_detail', models.TextField(blank=True, null=True)),
                ('whisky_region', models.CharField(blank=True, max_length=100, null=True)),
                ('whisky_rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'whisky',
                'verbose_name_plural': 'whiskies',
                'ordering': ['name'],
            },
        ),
    ]
