# Generated by Django 3.2.4 on 2021-09-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210905_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whisky',
            name='distillery',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='whisky',
            name='name_eng',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
