# Generated by Django 3.2.4 on 2021-07-05 08:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_whisky_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='credit',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='tier',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
