# Generated by Django 3.2.4 on 2021-07-10 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_0002_auto_20210627_2303_0002_whisky_confirmed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='review_rating',
        ),
        migrations.AddField(
            model_name='reaction',
            name='finish_rating',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='reaction',
            name='nose_rating',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='reaction',
            name='nose_tag',
            field=models.CharField(choices=[('Sweetness', 'Sweetness'), ('Fruity', 'Fruity'), ('Floral', 'Floral'), ('Body', 'Body'), ('Smoky', 'Smoky'), ('Tobacco', 'Tobacco'), ('Medicinal', 'Medicinal'), ('Winey', 'Winey'), ('Spicey', 'Spicey'), ('Malty', 'Malty'), ('Nutty', 'Nutty'), ('Honey', 'Honey')], default='Sweetness', max_length=9),
        ),
        migrations.AddField(
            model_name='reaction',
            name='taste_rating',
            field=models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='whisky',
            name='whisky_ratings',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
