# Generated by Django 3.2.4 on 2021-08-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210805_0000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whisky',
            old_name='name',
            new_name='name_eng',
        ),
        migrations.AddField(
            model_name='whisky',
            name='name_kor',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
