# Generated by Django 3.2.4 on 2021-07-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_reaction_taste_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reaction',
            name='finish_tag',
            field=models.CharField(choices=[('Nothing', 'Nothing'), ('Cereal', '곡물'), ('Woody', '나무'), ('Floral', '꽃'), ('Fruity', '과일'), ('Winey', '와인'), ('Sulphur', '유황'), ('Peaty', '피트'), ('Feinty', '후류')], default='Nothing', max_length=20),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='nose_tag',
            field=models.CharField(choices=[('Nothing', 'Nothing'), ('Cereal', '곡물'), ('Woody', '나무'), ('Floral', '꽃'), ('Fruity', '과일'), ('Winey', '와인'), ('Sulphur', '유황'), ('Peaty', '피트'), ('Feinty', '후류')], default='Nothing', max_length=20),
        ),
    ]
