# Generated by Django 3.1.6 on 2021-05-12 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_profile_nickname'),
        ('api', '0002_auto_20210506_2134'),
    ]

    operations = [
    ]
