# Generated by Django 3.2.4 on 2021-07-11 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210708_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whisky',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='whisky',
            name='whisky_region',
        ),
        migrations.AddField(
            model_name='whisky',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whisky',
            name='alcohol',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='whisky',
            name='bottle_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whisky',
            name='bottled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whisky',
            name='bottler',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whisky',
            name='cask',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whisky',
            name='casknumber',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='whisky',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whisky',
            name='distillery',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whisky',
            name='vintage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='whisky',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
