# Generated by Django 3.1.5 on 2021-05-13 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20210509_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='whisky',
            name='reaction_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_title', models.CharField(max_length=255)),
                ('review_body', models.TextField()),
                ('review_rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction', to=settings.AUTH_USER_MODEL)),
                ('whiskey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaction', to='api.whisky')),
            ],
            options={
                'ordering': ['-created_at'],
                'default_related_name': 'reaction',
            },
        ),
    ]
