# Generated by Django 3.1.5 on 2021-05-13 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210513_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reaction',
            old_name='whiskey',
            new_name='whisky',
        ),
    ]
