# Generated by Django 3.1.6 on 2021-05-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_merge_20210513_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whisky',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
