# Generated by Django 3.2.4 on 2021-07-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210711_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='eng_tag',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='tag',
            name='kor_tag',
            field=models.CharField(max_length=20),
        ),
    ]
