# Generated by Django 3.2.4 on 2021-08-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_whisky_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whisky',
            name='casknumber',
        ),
        migrations.AddField(
            model_name='whisky',
            name='bottle_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whisky',
            name='bottling_series',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whisky',
            name='cask_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whisky',
            name='cask_strength',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whisky',
            name='comment',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='whisky',
            name='independent_whisky',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whisky',
            name='natural_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whisky',
            name='non_chillfiltered',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whisky',
            name='region',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='whisky',
            name='single_cask',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whisky',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
