# Generated by Django 3.1.5 on 2021-05-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210516_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='media/default_image.png', null=True, upload_to=''),
        ),
    ]
