# Generated by Django 3.2.4 on 2021-09-02 16:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210828_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='finish_tag',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='nose_tag',
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='taste_tag',
        ),
        migrations.AddField(
            model_name='reaction',
            name='flavor_tag',
            field=models.ManyToManyField(related_name='flavor_tag', to='api.Tag'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='whisky',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', related_query_name='reactions', to='api.whisky'),
        ),
        migrations.CreateModel(
            name='ReactionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.validate_image_file_extension])),
                ('reaction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reaction_image', related_query_name='reaction_image', to='api.reaction')),
            ],
        ),
    ]
