# Generated by Django 3.1.6 on 2021-05-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_profile_profile_photo'),
        ('api', '0008_auto_20210513_0353'),
    ]

    operations = [
    ]
