# Generated by Django 3.2 on 2021-05-16 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210513_0353'),
        ('api', '0009_alter_profile_profile_photo'),
    ]

    operations = [
    ]
