# Generated by Django 3.1.5 on 2021-05-16 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_profile_profile_photo'),
        ('api', '0010_auto_20210516_1535'),
    ]

    operations = [
    ]
