# Generated by Django 3.1.6 on 2021-05-19 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20210516_1658'),
        ('api', '0010_merge_20210519_0242'),
    ]

    operations = [
    ]
