# Generated by Django 3.1.5 on 2021-05-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20210516_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.FileField(blank=True, default='media/default_image.png', null=True, upload_to=''),
        ),
    ]
