# Generated by Django 3.2 on 2021-05-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210520_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
