# Generated by Django 3.1.5 on 2021-05-16 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210516_1649'),
        ('api', '0008_auto_20210513_0353'),
    ]

    operations = [
    ]
