# Generated by Django 3.2 on 2021-05-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210520_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
