# Generated by Django 3.1.5 on 2021-05-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20210516_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='whisky',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='review_rating',
            field=models.IntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten')], default=5),
        ),
        migrations.AlterField(
            model_name='whisky',
            name='whisky_rating',
            field=models.IntegerField(null=True),
        ),
    ]
