# Generated by Django 3.2 on 2021-05-24 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_friendrequest_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='to_user',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
