# Generated by Django 3.1.5 on 2021-05-23 05:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210523_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whisky',
            name='reaction_count',
        ),
        migrations.AddField(
            model_name='whisky',
            name='rating_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='review_rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='whisky',
            name='whisky_rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
