# Generated by Django 3.1.5 on 2021-05-29 23:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0015_auto_20210523_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='whisky',
            options={},
        ),
        migrations.RenameField(
            model_name='whisky',
            old_name='rating_count',
            new_name='rating_counts',
        ),
        migrations.RemoveField(
            model_name='whisky',
            name='whisky_rating',
        ),
        migrations.AddField(
            model_name='whisky',
            name='whisky_ratings',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='review_rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='whisky',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.whisky'),
        ),
    ]
